# Generated by Django 4.0 on 2024-04-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('ac_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=10)),
            ],
        ),
    ]
